comp_i2c_pkg:
	vlog +incdir+$(ECE745_PROJECT_HOME)/verification_ip/ncsu_pkg +incdir+$(ECE745_PROJECT_HOME)/verification_ip/interface_packages/my_pkg $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/i2c_pkg/i2c_pkg.sv
	vlog $(ECE745_PROJECT_HOME)/verification_ip/interface_packages/i2c_pkg/src/i2c_if.sv
